//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalCasestudy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int BillId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> TreatmentId { get; set; }
        public Nullable<decimal> BillAmount { get; set; }
    
        public virtual PatientDetail PatientDetail { get; set; }
        public virtual TreatmentDetail TreatmentDetail { get; set; }
    }
}
